# Generated by Django 5.1.2 on 2024-11-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='implant',
            name='num_unita_operativo',
            field=models.IntegerField(default=0),
        ),
    ]
