# Generated by Django 5.1.2 on 2024-11-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('implants', '0002_implant_num_unita_operativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='implant',
            old_name='num_unita_operativo',
            new_name='num_unita_operativi',
        ),
    ]
