# Generated by Django 5.1.3 on 2024-12-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implants', '0003_rename_num_unita_operativo_implant_num_unita_operativi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='implant',
            old_name='name',
            new_name='implant_name',
        ),
        migrations.AlterField(
            model_name='implant',
            name='availability',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='implant',
            name='dateLastUpdate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='implant',
            name='num_unita_presenti',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='implant',
            name='operability',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='implant',
            name='rated_power',
            field=models.IntegerField(default=0),
        ),
    ]
