# Generated by Django 5.1.3 on 2024-12-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implants', '0004_rename_name_implant_implant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implant',
            name='availability',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='implant',
            name='num_unita_presenti',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='implant',
            name='operability',
            field=models.BooleanField(),
        ),
    ]
