# Generated by Django 5.2.4 on 2025-07-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implants', '0005_alter_implant_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implant',
            name='rated_power',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
    ]
